################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../Core/Inc/tensorflow/lite/micro/kernels/activations.cc \
../Core/Inc/tensorflow/lite/micro/kernels/activations_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/add.cc \
../Core/Inc/tensorflow/lite/micro/kernels/add_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/add_n.cc \
../Core/Inc/tensorflow/lite/micro/kernels/arg_min_max.cc \
../Core/Inc/tensorflow/lite/micro/kernels/assign_variable.cc \
../Core/Inc/tensorflow/lite/micro/kernels/batch_matmul.cc \
../Core/Inc/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../Core/Inc/tensorflow/lite/micro/kernels/broadcast_args.cc \
../Core/Inc/tensorflow/lite/micro/kernels/broadcast_to.cc \
../Core/Inc/tensorflow/lite/micro/kernels/call_once.cc \
../Core/Inc/tensorflow/lite/micro/kernels/cast.cc \
../Core/Inc/tensorflow/lite/micro/kernels/ceil.cc \
../Core/Inc/tensorflow/lite/micro/kernels/circular_buffer.cc \
../Core/Inc/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/comparisons.cc \
../Core/Inc/tensorflow/lite/micro/kernels/concatenation.cc \
../Core/Inc/tensorflow/lite/micro/kernels/conv.cc \
../Core/Inc/tensorflow/lite/micro/kernels/conv_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/cumsum.cc \
../Core/Inc/tensorflow/lite/micro/kernels/depth_to_space.cc \
../Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv.cc \
../Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/dequantize.cc \
../Core/Inc/tensorflow/lite/micro/kernels/dequantize_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../Core/Inc/tensorflow/lite/micro/kernels/div.cc \
../Core/Inc/tensorflow/lite/micro/kernels/elementwise.cc \
../Core/Inc/tensorflow/lite/micro/kernels/elu.cc \
../Core/Inc/tensorflow/lite/micro/kernels/embedding_lookup.cc \
../Core/Inc/tensorflow/lite/micro/kernels/ethosu.cc \
../Core/Inc/tensorflow/lite/micro/kernels/exp.cc \
../Core/Inc/tensorflow/lite/micro/kernels/expand_dims.cc \
../Core/Inc/tensorflow/lite/micro/kernels/fill.cc \
../Core/Inc/tensorflow/lite/micro/kernels/floor.cc \
../Core/Inc/tensorflow/lite/micro/kernels/floor_div.cc \
../Core/Inc/tensorflow/lite/micro/kernels/floor_mod.cc \
../Core/Inc/tensorflow/lite/micro/kernels/fully_connected.cc \
../Core/Inc/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/gather.cc \
../Core/Inc/tensorflow/lite/micro/kernels/gather_nd.cc \
../Core/Inc/tensorflow/lite/micro/kernels/hard_swish.cc \
../Core/Inc/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/if.cc \
../Core/Inc/tensorflow/lite/micro/kernels/kernel_runner.cc \
../Core/Inc/tensorflow/lite/micro/kernels/kernel_util.cc \
../Core/Inc/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../Core/Inc/tensorflow/lite/micro/kernels/l2norm.cc \
../Core/Inc/tensorflow/lite/micro/kernels/leaky_relu.cc \
../Core/Inc/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/log_softmax.cc \
../Core/Inc/tensorflow/lite/micro/kernels/logical.cc \
../Core/Inc/tensorflow/lite/micro/kernels/logical_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/logistic.cc \
../Core/Inc/tensorflow/lite/micro/kernels/logistic_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/lstm_eval.cc \
../Core/Inc/tensorflow/lite/micro/kernels/lstm_eval_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../Core/Inc/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../Core/Inc/tensorflow/lite/micro/kernels/mirror_pad.cc \
../Core/Inc/tensorflow/lite/micro/kernels/mul.cc \
../Core/Inc/tensorflow/lite/micro/kernels/mul_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/neg.cc \
../Core/Inc/tensorflow/lite/micro/kernels/pack.cc \
../Core/Inc/tensorflow/lite/micro/kernels/pad.cc \
../Core/Inc/tensorflow/lite/micro/kernels/pooling.cc \
../Core/Inc/tensorflow/lite/micro/kernels/pooling_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/prelu.cc \
../Core/Inc/tensorflow/lite/micro/kernels/prelu_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/quantize.cc \
../Core/Inc/tensorflow/lite/micro/kernels/quantize_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/read_variable.cc \
../Core/Inc/tensorflow/lite/micro/kernels/reduce.cc \
../Core/Inc/tensorflow/lite/micro/kernels/reduce_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/reshape.cc \
../Core/Inc/tensorflow/lite/micro/kernels/reshape_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../Core/Inc/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../Core/Inc/tensorflow/lite/micro/kernels/round.cc \
../Core/Inc/tensorflow/lite/micro/kernels/select.cc \
../Core/Inc/tensorflow/lite/micro/kernels/shape.cc \
../Core/Inc/tensorflow/lite/micro/kernels/slice.cc \
../Core/Inc/tensorflow/lite/micro/kernels/softmax.cc \
../Core/Inc/tensorflow/lite/micro/kernels/softmax_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../Core/Inc/tensorflow/lite/micro/kernels/space_to_depth.cc \
../Core/Inc/tensorflow/lite/micro/kernels/split.cc \
../Core/Inc/tensorflow/lite/micro/kernels/split_v.cc \
../Core/Inc/tensorflow/lite/micro/kernels/squared_difference.cc \
../Core/Inc/tensorflow/lite/micro/kernels/squeeze.cc \
../Core/Inc/tensorflow/lite/micro/kernels/strided_slice.cc \
../Core/Inc/tensorflow/lite/micro/kernels/strided_slice_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/sub.cc \
../Core/Inc/tensorflow/lite/micro/kernels/sub_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/svdf.cc \
../Core/Inc/tensorflow/lite/micro/kernels/svdf_common.cc \
../Core/Inc/tensorflow/lite/micro/kernels/tanh.cc \
../Core/Inc/tensorflow/lite/micro/kernels/transpose.cc \
../Core/Inc/tensorflow/lite/micro/kernels/transpose_conv.cc \
../Core/Inc/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cc \
../Core/Inc/tensorflow/lite/micro/kernels/unpack.cc \
../Core/Inc/tensorflow/lite/micro/kernels/var_handle.cc \
../Core/Inc/tensorflow/lite/micro/kernels/while.cc \
../Core/Inc/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./Core/Inc/tensorflow/lite/micro/kernels/activations.d \
./Core/Inc/tensorflow/lite/micro/kernels/activations_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/add.d \
./Core/Inc/tensorflow/lite/micro/kernels/add_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/add_n.d \
./Core/Inc/tensorflow/lite/micro/kernels/arg_min_max.d \
./Core/Inc/tensorflow/lite/micro/kernels/assign_variable.d \
./Core/Inc/tensorflow/lite/micro/kernels/batch_matmul.d \
./Core/Inc/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./Core/Inc/tensorflow/lite/micro/kernels/broadcast_args.d \
./Core/Inc/tensorflow/lite/micro/kernels/broadcast_to.d \
./Core/Inc/tensorflow/lite/micro/kernels/call_once.d \
./Core/Inc/tensorflow/lite/micro/kernels/cast.d \
./Core/Inc/tensorflow/lite/micro/kernels/ceil.d \
./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer.d \
./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/comparisons.d \
./Core/Inc/tensorflow/lite/micro/kernels/concatenation.d \
./Core/Inc/tensorflow/lite/micro/kernels/conv.d \
./Core/Inc/tensorflow/lite/micro/kernels/conv_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/cumsum.d \
./Core/Inc/tensorflow/lite/micro/kernels/depth_to_space.d \
./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv.d \
./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/dequantize.d \
./Core/Inc/tensorflow/lite/micro/kernels/dequantize_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/detection_postprocess.d \
./Core/Inc/tensorflow/lite/micro/kernels/div.d \
./Core/Inc/tensorflow/lite/micro/kernels/elementwise.d \
./Core/Inc/tensorflow/lite/micro/kernels/elu.d \
./Core/Inc/tensorflow/lite/micro/kernels/embedding_lookup.d \
./Core/Inc/tensorflow/lite/micro/kernels/ethosu.d \
./Core/Inc/tensorflow/lite/micro/kernels/exp.d \
./Core/Inc/tensorflow/lite/micro/kernels/expand_dims.d \
./Core/Inc/tensorflow/lite/micro/kernels/fill.d \
./Core/Inc/tensorflow/lite/micro/kernels/floor.d \
./Core/Inc/tensorflow/lite/micro/kernels/floor_div.d \
./Core/Inc/tensorflow/lite/micro/kernels/floor_mod.d \
./Core/Inc/tensorflow/lite/micro/kernels/fully_connected.d \
./Core/Inc/tensorflow/lite/micro/kernels/fully_connected_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/gather.d \
./Core/Inc/tensorflow/lite/micro/kernels/gather_nd.d \
./Core/Inc/tensorflow/lite/micro/kernels/hard_swish.d \
./Core/Inc/tensorflow/lite/micro/kernels/hard_swish_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/if.d \
./Core/Inc/tensorflow/lite/micro/kernels/kernel_runner.d \
./Core/Inc/tensorflow/lite/micro/kernels/kernel_util.d \
./Core/Inc/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./Core/Inc/tensorflow/lite/micro/kernels/l2norm.d \
./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu.d \
./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/log_softmax.d \
./Core/Inc/tensorflow/lite/micro/kernels/logical.d \
./Core/Inc/tensorflow/lite/micro/kernels/logical_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/logistic.d \
./Core/Inc/tensorflow/lite/micro/kernels/logistic_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval.d \
./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/maximum_minimum.d \
./Core/Inc/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./Core/Inc/tensorflow/lite/micro/kernels/mirror_pad.d \
./Core/Inc/tensorflow/lite/micro/kernels/mul.d \
./Core/Inc/tensorflow/lite/micro/kernels/mul_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/neg.d \
./Core/Inc/tensorflow/lite/micro/kernels/pack.d \
./Core/Inc/tensorflow/lite/micro/kernels/pad.d \
./Core/Inc/tensorflow/lite/micro/kernels/pooling.d \
./Core/Inc/tensorflow/lite/micro/kernels/pooling_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/prelu.d \
./Core/Inc/tensorflow/lite/micro/kernels/prelu_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/quantize.d \
./Core/Inc/tensorflow/lite/micro/kernels/quantize_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/read_variable.d \
./Core/Inc/tensorflow/lite/micro/kernels/reduce.d \
./Core/Inc/tensorflow/lite/micro/kernels/reduce_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/reshape.d \
./Core/Inc/tensorflow/lite/micro/kernels/reshape_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/resize_bilinear.d \
./Core/Inc/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./Core/Inc/tensorflow/lite/micro/kernels/round.d \
./Core/Inc/tensorflow/lite/micro/kernels/select.d \
./Core/Inc/tensorflow/lite/micro/kernels/shape.d \
./Core/Inc/tensorflow/lite/micro/kernels/slice.d \
./Core/Inc/tensorflow/lite/micro/kernels/softmax.d \
./Core/Inc/tensorflow/lite/micro/kernels/softmax_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./Core/Inc/tensorflow/lite/micro/kernels/space_to_depth.d \
./Core/Inc/tensorflow/lite/micro/kernels/split.d \
./Core/Inc/tensorflow/lite/micro/kernels/split_v.d \
./Core/Inc/tensorflow/lite/micro/kernels/squared_difference.d \
./Core/Inc/tensorflow/lite/micro/kernels/squeeze.d \
./Core/Inc/tensorflow/lite/micro/kernels/strided_slice.d \
./Core/Inc/tensorflow/lite/micro/kernels/strided_slice_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/sub.d \
./Core/Inc/tensorflow/lite/micro/kernels/sub_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/svdf.d \
./Core/Inc/tensorflow/lite/micro/kernels/svdf_common.d \
./Core/Inc/tensorflow/lite/micro/kernels/tanh.d \
./Core/Inc/tensorflow/lite/micro/kernels/transpose.d \
./Core/Inc/tensorflow/lite/micro/kernels/transpose_conv.d \
./Core/Inc/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d \
./Core/Inc/tensorflow/lite/micro/kernels/unpack.d \
./Core/Inc/tensorflow/lite/micro/kernels/var_handle.d \
./Core/Inc/tensorflow/lite/micro/kernels/while.d \
./Core/Inc/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./Core/Inc/tensorflow/lite/micro/kernels/activations.o \
./Core/Inc/tensorflow/lite/micro/kernels/activations_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/add.o \
./Core/Inc/tensorflow/lite/micro/kernels/add_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/add_n.o \
./Core/Inc/tensorflow/lite/micro/kernels/arg_min_max.o \
./Core/Inc/tensorflow/lite/micro/kernels/assign_variable.o \
./Core/Inc/tensorflow/lite/micro/kernels/batch_matmul.o \
./Core/Inc/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./Core/Inc/tensorflow/lite/micro/kernels/broadcast_args.o \
./Core/Inc/tensorflow/lite/micro/kernels/broadcast_to.o \
./Core/Inc/tensorflow/lite/micro/kernels/call_once.o \
./Core/Inc/tensorflow/lite/micro/kernels/cast.o \
./Core/Inc/tensorflow/lite/micro/kernels/ceil.o \
./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer.o \
./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/comparisons.o \
./Core/Inc/tensorflow/lite/micro/kernels/concatenation.o \
./Core/Inc/tensorflow/lite/micro/kernels/conv.o \
./Core/Inc/tensorflow/lite/micro/kernels/conv_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/cumsum.o \
./Core/Inc/tensorflow/lite/micro/kernels/depth_to_space.o \
./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv.o \
./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/dequantize.o \
./Core/Inc/tensorflow/lite/micro/kernels/dequantize_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/detection_postprocess.o \
./Core/Inc/tensorflow/lite/micro/kernels/div.o \
./Core/Inc/tensorflow/lite/micro/kernels/elementwise.o \
./Core/Inc/tensorflow/lite/micro/kernels/elu.o \
./Core/Inc/tensorflow/lite/micro/kernels/embedding_lookup.o \
./Core/Inc/tensorflow/lite/micro/kernels/ethosu.o \
./Core/Inc/tensorflow/lite/micro/kernels/exp.o \
./Core/Inc/tensorflow/lite/micro/kernels/expand_dims.o \
./Core/Inc/tensorflow/lite/micro/kernels/fill.o \
./Core/Inc/tensorflow/lite/micro/kernels/floor.o \
./Core/Inc/tensorflow/lite/micro/kernels/floor_div.o \
./Core/Inc/tensorflow/lite/micro/kernels/floor_mod.o \
./Core/Inc/tensorflow/lite/micro/kernels/fully_connected.o \
./Core/Inc/tensorflow/lite/micro/kernels/fully_connected_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/gather.o \
./Core/Inc/tensorflow/lite/micro/kernels/gather_nd.o \
./Core/Inc/tensorflow/lite/micro/kernels/hard_swish.o \
./Core/Inc/tensorflow/lite/micro/kernels/hard_swish_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/if.o \
./Core/Inc/tensorflow/lite/micro/kernels/kernel_runner.o \
./Core/Inc/tensorflow/lite/micro/kernels/kernel_util.o \
./Core/Inc/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./Core/Inc/tensorflow/lite/micro/kernels/l2norm.o \
./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu.o \
./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/log_softmax.o \
./Core/Inc/tensorflow/lite/micro/kernels/logical.o \
./Core/Inc/tensorflow/lite/micro/kernels/logical_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/logistic.o \
./Core/Inc/tensorflow/lite/micro/kernels/logistic_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval.o \
./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/maximum_minimum.o \
./Core/Inc/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./Core/Inc/tensorflow/lite/micro/kernels/mirror_pad.o \
./Core/Inc/tensorflow/lite/micro/kernels/mul.o \
./Core/Inc/tensorflow/lite/micro/kernels/mul_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/neg.o \
./Core/Inc/tensorflow/lite/micro/kernels/pack.o \
./Core/Inc/tensorflow/lite/micro/kernels/pad.o \
./Core/Inc/tensorflow/lite/micro/kernels/pooling.o \
./Core/Inc/tensorflow/lite/micro/kernels/pooling_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/prelu.o \
./Core/Inc/tensorflow/lite/micro/kernels/prelu_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/quantize.o \
./Core/Inc/tensorflow/lite/micro/kernels/quantize_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/read_variable.o \
./Core/Inc/tensorflow/lite/micro/kernels/reduce.o \
./Core/Inc/tensorflow/lite/micro/kernels/reduce_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/reshape.o \
./Core/Inc/tensorflow/lite/micro/kernels/reshape_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/resize_bilinear.o \
./Core/Inc/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./Core/Inc/tensorflow/lite/micro/kernels/round.o \
./Core/Inc/tensorflow/lite/micro/kernels/select.o \
./Core/Inc/tensorflow/lite/micro/kernels/shape.o \
./Core/Inc/tensorflow/lite/micro/kernels/slice.o \
./Core/Inc/tensorflow/lite/micro/kernels/softmax.o \
./Core/Inc/tensorflow/lite/micro/kernels/softmax_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./Core/Inc/tensorflow/lite/micro/kernels/space_to_depth.o \
./Core/Inc/tensorflow/lite/micro/kernels/split.o \
./Core/Inc/tensorflow/lite/micro/kernels/split_v.o \
./Core/Inc/tensorflow/lite/micro/kernels/squared_difference.o \
./Core/Inc/tensorflow/lite/micro/kernels/squeeze.o \
./Core/Inc/tensorflow/lite/micro/kernels/strided_slice.o \
./Core/Inc/tensorflow/lite/micro/kernels/strided_slice_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/sub.o \
./Core/Inc/tensorflow/lite/micro/kernels/sub_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/svdf.o \
./Core/Inc/tensorflow/lite/micro/kernels/svdf_common.o \
./Core/Inc/tensorflow/lite/micro/kernels/tanh.o \
./Core/Inc/tensorflow/lite/micro/kernels/transpose.o \
./Core/Inc/tensorflow/lite/micro/kernels/transpose_conv.o \
./Core/Inc/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o \
./Core/Inc/tensorflow/lite/micro/kernels/unpack.o \
./Core/Inc/tensorflow/lite/micro/kernels/var_handle.o \
./Core/Inc/tensorflow/lite/micro/kernels/while.o \
./Core/Inc/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
Core/Inc/tensorflow/lite/micro/kernels/%.o Core/Inc/tensorflow/lite/micro/kernels/%.su Core/Inc/tensorflow/lite/micro/kernels/%.cyclo: ../Core/Inc/tensorflow/lite/micro/kernels/%.cc Core/Inc/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H753xx -DTF_LITE_STATIC_MEMORY -c -I../Core/Inc -IC:/Users/Administrator/STM32Cube/Repository/STM32Cube_FW_H7_V1.11.1/Drivers/STM32H7xx_HAL_Driver/Inc -IC:/Users/Administrator/STM32Cube/Repository/STM32Cube_FW_H7_V1.11.1/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -IC:/Users/Administrator/STM32Cube/Repository/STM32Cube_FW_H7_V1.11.1/Drivers/CMSIS/Device/ST/STM32H7xx/Include -IC:/Users/Administrator/STM32Cube/Repository/STM32Cube_FW_H7_V1.11.1/Drivers/CMSIS/Include -I../Core/Inc/kissfft -I../Core/Inc/person_detection -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-Inc-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-Core-2f-Inc-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./Core/Inc/tensorflow/lite/micro/kernels/activations.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/activations.d ./Core/Inc/tensorflow/lite/micro/kernels/activations.o ./Core/Inc/tensorflow/lite/micro/kernels/activations.su ./Core/Inc/tensorflow/lite/micro/kernels/activations_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/activations_common.d ./Core/Inc/tensorflow/lite/micro/kernels/activations_common.o ./Core/Inc/tensorflow/lite/micro/kernels/activations_common.su ./Core/Inc/tensorflow/lite/micro/kernels/add.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/add.d ./Core/Inc/tensorflow/lite/micro/kernels/add.o ./Core/Inc/tensorflow/lite/micro/kernels/add.su ./Core/Inc/tensorflow/lite/micro/kernels/add_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/add_common.d ./Core/Inc/tensorflow/lite/micro/kernels/add_common.o ./Core/Inc/tensorflow/lite/micro/kernels/add_common.su ./Core/Inc/tensorflow/lite/micro/kernels/add_n.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/add_n.d ./Core/Inc/tensorflow/lite/micro/kernels/add_n.o ./Core/Inc/tensorflow/lite/micro/kernels/add_n.su ./Core/Inc/tensorflow/lite/micro/kernels/arg_min_max.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/arg_min_max.d ./Core/Inc/tensorflow/lite/micro/kernels/arg_min_max.o ./Core/Inc/tensorflow/lite/micro/kernels/arg_min_max.su ./Core/Inc/tensorflow/lite/micro/kernels/assign_variable.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/assign_variable.d ./Core/Inc/tensorflow/lite/micro/kernels/assign_variable.o ./Core/Inc/tensorflow/lite/micro/kernels/assign_variable.su ./Core/Inc/tensorflow/lite/micro/kernels/batch_matmul.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/batch_matmul.d ./Core/Inc/tensorflow/lite/micro/kernels/batch_matmul.o ./Core/Inc/tensorflow/lite/micro/kernels/batch_matmul.su ./Core/Inc/tensorflow/lite/micro/kernels/batch_to_space_nd.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./Core/Inc/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./Core/Inc/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./Core/Inc/tensorflow/lite/micro/kernels/broadcast_args.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/broadcast_args.d ./Core/Inc/tensorflow/lite/micro/kernels/broadcast_args.o ./Core/Inc/tensorflow/lite/micro/kernels/broadcast_args.su ./Core/Inc/tensorflow/lite/micro/kernels/broadcast_to.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/broadcast_to.d ./Core/Inc/tensorflow/lite/micro/kernels/broadcast_to.o ./Core/Inc/tensorflow/lite/micro/kernels/broadcast_to.su ./Core/Inc/tensorflow/lite/micro/kernels/call_once.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/call_once.d ./Core/Inc/tensorflow/lite/micro/kernels/call_once.o ./Core/Inc/tensorflow/lite/micro/kernels/call_once.su ./Core/Inc/tensorflow/lite/micro/kernels/cast.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/cast.d ./Core/Inc/tensorflow/lite/micro/kernels/cast.o ./Core/Inc/tensorflow/lite/micro/kernels/cast.su ./Core/Inc/tensorflow/lite/micro/kernels/ceil.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/ceil.d ./Core/Inc/tensorflow/lite/micro/kernels/ceil.o ./Core/Inc/tensorflow/lite/micro/kernels/ceil.su ./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer.d ./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer.o ./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer.su ./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer_common.d ./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer_common.o ./Core/Inc/tensorflow/lite/micro/kernels/circular_buffer_common.su ./Core/Inc/tensorflow/lite/micro/kernels/comparisons.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/comparisons.d ./Core/Inc/tensorflow/lite/micro/kernels/comparisons.o ./Core/Inc/tensorflow/lite/micro/kernels/comparisons.su ./Core/Inc/tensorflow/lite/micro/kernels/concatenation.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/concatenation.d ./Core/Inc/tensorflow/lite/micro/kernels/concatenation.o ./Core/Inc/tensorflow/lite/micro/kernels/concatenation.su ./Core/Inc/tensorflow/lite/micro/kernels/conv.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/conv.d ./Core/Inc/tensorflow/lite/micro/kernels/conv.o ./Core/Inc/tensorflow/lite/micro/kernels/conv.su ./Core/Inc/tensorflow/lite/micro/kernels/conv_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/conv_common.d ./Core/Inc/tensorflow/lite/micro/kernels/conv_common.o ./Core/Inc/tensorflow/lite/micro/kernels/conv_common.su ./Core/Inc/tensorflow/lite/micro/kernels/cumsum.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/cumsum.d ./Core/Inc/tensorflow/lite/micro/kernels/cumsum.o ./Core/Inc/tensorflow/lite/micro/kernels/cumsum.su ./Core/Inc/tensorflow/lite/micro/kernels/depth_to_space.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/depth_to_space.d ./Core/Inc/tensorflow/lite/micro/kernels/depth_to_space.o ./Core/Inc/tensorflow/lite/micro/kernels/depth_to_space.su ./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv.d ./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv.o ./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv.su ./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./Core/Inc/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./Core/Inc/tensorflow/lite/micro/kernels/dequantize.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/dequantize.d ./Core/Inc/tensorflow/lite/micro/kernels/dequantize.o ./Core/Inc/tensorflow/lite/micro/kernels/dequantize.su ./Core/Inc/tensorflow/lite/micro/kernels/dequantize_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/dequantize_common.d ./Core/Inc/tensorflow/lite/micro/kernels/dequantize_common.o ./Core/Inc/tensorflow/lite/micro/kernels/dequantize_common.su ./Core/Inc/tensorflow/lite/micro/kernels/detection_postprocess.cyclo
	-$(RM) ./Core/Inc/tensorflow/lite/micro/kernels/detection_postprocess.d ./Core/Inc/tensorflow/lite/micro/kernels/detection_postprocess.o ./Core/Inc/tensorflow/lite/micro/kernels/detection_postprocess.su ./Core/Inc/tensorflow/lite/micro/kernels/div.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/div.d ./Core/Inc/tensorflow/lite/micro/kernels/div.o ./Core/Inc/tensorflow/lite/micro/kernels/div.su ./Core/Inc/tensorflow/lite/micro/kernels/elementwise.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/elementwise.d ./Core/Inc/tensorflow/lite/micro/kernels/elementwise.o ./Core/Inc/tensorflow/lite/micro/kernels/elementwise.su ./Core/Inc/tensorflow/lite/micro/kernels/elu.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/elu.d ./Core/Inc/tensorflow/lite/micro/kernels/elu.o ./Core/Inc/tensorflow/lite/micro/kernels/elu.su ./Core/Inc/tensorflow/lite/micro/kernels/embedding_lookup.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/embedding_lookup.d ./Core/Inc/tensorflow/lite/micro/kernels/embedding_lookup.o ./Core/Inc/tensorflow/lite/micro/kernels/embedding_lookup.su ./Core/Inc/tensorflow/lite/micro/kernels/ethosu.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/ethosu.d ./Core/Inc/tensorflow/lite/micro/kernels/ethosu.o ./Core/Inc/tensorflow/lite/micro/kernels/ethosu.su ./Core/Inc/tensorflow/lite/micro/kernels/exp.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/exp.d ./Core/Inc/tensorflow/lite/micro/kernels/exp.o ./Core/Inc/tensorflow/lite/micro/kernels/exp.su ./Core/Inc/tensorflow/lite/micro/kernels/expand_dims.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/expand_dims.d ./Core/Inc/tensorflow/lite/micro/kernels/expand_dims.o ./Core/Inc/tensorflow/lite/micro/kernels/expand_dims.su ./Core/Inc/tensorflow/lite/micro/kernels/fill.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/fill.d ./Core/Inc/tensorflow/lite/micro/kernels/fill.o ./Core/Inc/tensorflow/lite/micro/kernels/fill.su ./Core/Inc/tensorflow/lite/micro/kernels/floor.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/floor.d ./Core/Inc/tensorflow/lite/micro/kernels/floor.o ./Core/Inc/tensorflow/lite/micro/kernels/floor.su ./Core/Inc/tensorflow/lite/micro/kernels/floor_div.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/floor_div.d ./Core/Inc/tensorflow/lite/micro/kernels/floor_div.o ./Core/Inc/tensorflow/lite/micro/kernels/floor_div.su ./Core/Inc/tensorflow/lite/micro/kernels/floor_mod.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/floor_mod.d ./Core/Inc/tensorflow/lite/micro/kernels/floor_mod.o ./Core/Inc/tensorflow/lite/micro/kernels/floor_mod.su ./Core/Inc/tensorflow/lite/micro/kernels/fully_connected.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/fully_connected.d ./Core/Inc/tensorflow/lite/micro/kernels/fully_connected.o ./Core/Inc/tensorflow/lite/micro/kernels/fully_connected.su ./Core/Inc/tensorflow/lite/micro/kernels/fully_connected_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/fully_connected_common.d ./Core/Inc/tensorflow/lite/micro/kernels/fully_connected_common.o ./Core/Inc/tensorflow/lite/micro/kernels/fully_connected_common.su ./Core/Inc/tensorflow/lite/micro/kernels/gather.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/gather.d ./Core/Inc/tensorflow/lite/micro/kernels/gather.o ./Core/Inc/tensorflow/lite/micro/kernels/gather.su ./Core/Inc/tensorflow/lite/micro/kernels/gather_nd.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/gather_nd.d ./Core/Inc/tensorflow/lite/micro/kernels/gather_nd.o ./Core/Inc/tensorflow/lite/micro/kernels/gather_nd.su ./Core/Inc/tensorflow/lite/micro/kernels/hard_swish.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/hard_swish.d ./Core/Inc/tensorflow/lite/micro/kernels/hard_swish.o ./Core/Inc/tensorflow/lite/micro/kernels/hard_swish.su ./Core/Inc/tensorflow/lite/micro/kernels/hard_swish_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/hard_swish_common.d ./Core/Inc/tensorflow/lite/micro/kernels/hard_swish_common.o ./Core/Inc/tensorflow/lite/micro/kernels/hard_swish_common.su ./Core/Inc/tensorflow/lite/micro/kernels/if.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/if.d ./Core/Inc/tensorflow/lite/micro/kernels/if.o ./Core/Inc/tensorflow/lite/micro/kernels/if.su ./Core/Inc/tensorflow/lite/micro/kernels/kernel_runner.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/kernel_runner.d ./Core/Inc/tensorflow/lite/micro/kernels/kernel_runner.o ./Core/Inc/tensorflow/lite/micro/kernels/kernel_runner.su ./Core/Inc/tensorflow/lite/micro/kernels/kernel_util.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/kernel_util.d ./Core/Inc/tensorflow/lite/micro/kernels/kernel_util.o ./Core/Inc/tensorflow/lite/micro/kernels/kernel_util.su ./Core/Inc/tensorflow/lite/micro/kernels/l2_pool_2d.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/l2_pool_2d.d ./Core/Inc/tensorflow/lite/micro/kernels/l2_pool_2d.o ./Core/Inc/tensorflow/lite/micro/kernels/l2_pool_2d.su ./Core/Inc/tensorflow/lite/micro/kernels/l2norm.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/l2norm.d ./Core/Inc/tensorflow/lite/micro/kernels/l2norm.o ./Core/Inc/tensorflow/lite/micro/kernels/l2norm.su ./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu.d ./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu.o ./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu.su ./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu_common.d ./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu_common.o ./Core/Inc/tensorflow/lite/micro/kernels/leaky_relu_common.su ./Core/Inc/tensorflow/lite/micro/kernels/log_softmax.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/log_softmax.d ./Core/Inc/tensorflow/lite/micro/kernels/log_softmax.o ./Core/Inc/tensorflow/lite/micro/kernels/log_softmax.su ./Core/Inc/tensorflow/lite/micro/kernels/logical.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/logical.d ./Core/Inc/tensorflow/lite/micro/kernels/logical.o ./Core/Inc/tensorflow/lite/micro/kernels/logical.su ./Core/Inc/tensorflow/lite/micro/kernels/logical_common.cyclo
	-$(RM) ./Core/Inc/tensorflow/lite/micro/kernels/logical_common.d ./Core/Inc/tensorflow/lite/micro/kernels/logical_common.o ./Core/Inc/tensorflow/lite/micro/kernels/logical_common.su ./Core/Inc/tensorflow/lite/micro/kernels/logistic.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/logistic.d ./Core/Inc/tensorflow/lite/micro/kernels/logistic.o ./Core/Inc/tensorflow/lite/micro/kernels/logistic.su ./Core/Inc/tensorflow/lite/micro/kernels/logistic_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/logistic_common.d ./Core/Inc/tensorflow/lite/micro/kernels/logistic_common.o ./Core/Inc/tensorflow/lite/micro/kernels/logistic_common.su ./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval.d ./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval.o ./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval.su ./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval_common.d ./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval_common.o ./Core/Inc/tensorflow/lite/micro/kernels/lstm_eval_common.su ./Core/Inc/tensorflow/lite/micro/kernels/maximum_minimum.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/maximum_minimum.d ./Core/Inc/tensorflow/lite/micro/kernels/maximum_minimum.o ./Core/Inc/tensorflow/lite/micro/kernels/maximum_minimum.su ./Core/Inc/tensorflow/lite/micro/kernels/micro_tensor_utils.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./Core/Inc/tensorflow/lite/micro/kernels/micro_tensor_utils.o ./Core/Inc/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./Core/Inc/tensorflow/lite/micro/kernels/mirror_pad.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/mirror_pad.d ./Core/Inc/tensorflow/lite/micro/kernels/mirror_pad.o ./Core/Inc/tensorflow/lite/micro/kernels/mirror_pad.su ./Core/Inc/tensorflow/lite/micro/kernels/mul.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/mul.d ./Core/Inc/tensorflow/lite/micro/kernels/mul.o ./Core/Inc/tensorflow/lite/micro/kernels/mul.su ./Core/Inc/tensorflow/lite/micro/kernels/mul_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/mul_common.d ./Core/Inc/tensorflow/lite/micro/kernels/mul_common.o ./Core/Inc/tensorflow/lite/micro/kernels/mul_common.su ./Core/Inc/tensorflow/lite/micro/kernels/neg.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/neg.d ./Core/Inc/tensorflow/lite/micro/kernels/neg.o ./Core/Inc/tensorflow/lite/micro/kernels/neg.su ./Core/Inc/tensorflow/lite/micro/kernels/pack.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/pack.d ./Core/Inc/tensorflow/lite/micro/kernels/pack.o ./Core/Inc/tensorflow/lite/micro/kernels/pack.su ./Core/Inc/tensorflow/lite/micro/kernels/pad.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/pad.d ./Core/Inc/tensorflow/lite/micro/kernels/pad.o ./Core/Inc/tensorflow/lite/micro/kernels/pad.su ./Core/Inc/tensorflow/lite/micro/kernels/pooling.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/pooling.d ./Core/Inc/tensorflow/lite/micro/kernels/pooling.o ./Core/Inc/tensorflow/lite/micro/kernels/pooling.su ./Core/Inc/tensorflow/lite/micro/kernels/pooling_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/pooling_common.d ./Core/Inc/tensorflow/lite/micro/kernels/pooling_common.o ./Core/Inc/tensorflow/lite/micro/kernels/pooling_common.su ./Core/Inc/tensorflow/lite/micro/kernels/prelu.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/prelu.d ./Core/Inc/tensorflow/lite/micro/kernels/prelu.o ./Core/Inc/tensorflow/lite/micro/kernels/prelu.su ./Core/Inc/tensorflow/lite/micro/kernels/prelu_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/prelu_common.d ./Core/Inc/tensorflow/lite/micro/kernels/prelu_common.o ./Core/Inc/tensorflow/lite/micro/kernels/prelu_common.su ./Core/Inc/tensorflow/lite/micro/kernels/quantize.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/quantize.d ./Core/Inc/tensorflow/lite/micro/kernels/quantize.o ./Core/Inc/tensorflow/lite/micro/kernels/quantize.su ./Core/Inc/tensorflow/lite/micro/kernels/quantize_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/quantize_common.d ./Core/Inc/tensorflow/lite/micro/kernels/quantize_common.o ./Core/Inc/tensorflow/lite/micro/kernels/quantize_common.su ./Core/Inc/tensorflow/lite/micro/kernels/read_variable.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/read_variable.d ./Core/Inc/tensorflow/lite/micro/kernels/read_variable.o ./Core/Inc/tensorflow/lite/micro/kernels/read_variable.su ./Core/Inc/tensorflow/lite/micro/kernels/reduce.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/reduce.d ./Core/Inc/tensorflow/lite/micro/kernels/reduce.o ./Core/Inc/tensorflow/lite/micro/kernels/reduce.su ./Core/Inc/tensorflow/lite/micro/kernels/reduce_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/reduce_common.d ./Core/Inc/tensorflow/lite/micro/kernels/reduce_common.o ./Core/Inc/tensorflow/lite/micro/kernels/reduce_common.su ./Core/Inc/tensorflow/lite/micro/kernels/reshape.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/reshape.d ./Core/Inc/tensorflow/lite/micro/kernels/reshape.o ./Core/Inc/tensorflow/lite/micro/kernels/reshape.su ./Core/Inc/tensorflow/lite/micro/kernels/reshape_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/reshape_common.d ./Core/Inc/tensorflow/lite/micro/kernels/reshape_common.o ./Core/Inc/tensorflow/lite/micro/kernels/reshape_common.su ./Core/Inc/tensorflow/lite/micro/kernels/resize_bilinear.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/resize_bilinear.d ./Core/Inc/tensorflow/lite/micro/kernels/resize_bilinear.o ./Core/Inc/tensorflow/lite/micro/kernels/resize_bilinear.su ./Core/Inc/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./Core/Inc/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./Core/Inc/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./Core/Inc/tensorflow/lite/micro/kernels/round.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/round.d ./Core/Inc/tensorflow/lite/micro/kernels/round.o ./Core/Inc/tensorflow/lite/micro/kernels/round.su
	-$(RM) ./Core/Inc/tensorflow/lite/micro/kernels/select.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/select.d ./Core/Inc/tensorflow/lite/micro/kernels/select.o ./Core/Inc/tensorflow/lite/micro/kernels/select.su ./Core/Inc/tensorflow/lite/micro/kernels/shape.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/shape.d ./Core/Inc/tensorflow/lite/micro/kernels/shape.o ./Core/Inc/tensorflow/lite/micro/kernels/shape.su ./Core/Inc/tensorflow/lite/micro/kernels/slice.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/slice.d ./Core/Inc/tensorflow/lite/micro/kernels/slice.o ./Core/Inc/tensorflow/lite/micro/kernels/slice.su ./Core/Inc/tensorflow/lite/micro/kernels/softmax.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/softmax.d ./Core/Inc/tensorflow/lite/micro/kernels/softmax.o ./Core/Inc/tensorflow/lite/micro/kernels/softmax.su ./Core/Inc/tensorflow/lite/micro/kernels/softmax_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/softmax_common.d ./Core/Inc/tensorflow/lite/micro/kernels/softmax_common.o ./Core/Inc/tensorflow/lite/micro/kernels/softmax_common.su ./Core/Inc/tensorflow/lite/micro/kernels/space_to_batch_nd.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./Core/Inc/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./Core/Inc/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./Core/Inc/tensorflow/lite/micro/kernels/space_to_depth.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/space_to_depth.d ./Core/Inc/tensorflow/lite/micro/kernels/space_to_depth.o ./Core/Inc/tensorflow/lite/micro/kernels/space_to_depth.su ./Core/Inc/tensorflow/lite/micro/kernels/split.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/split.d ./Core/Inc/tensorflow/lite/micro/kernels/split.o ./Core/Inc/tensorflow/lite/micro/kernels/split.su ./Core/Inc/tensorflow/lite/micro/kernels/split_v.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/split_v.d ./Core/Inc/tensorflow/lite/micro/kernels/split_v.o ./Core/Inc/tensorflow/lite/micro/kernels/split_v.su ./Core/Inc/tensorflow/lite/micro/kernels/squared_difference.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/squared_difference.d ./Core/Inc/tensorflow/lite/micro/kernels/squared_difference.o ./Core/Inc/tensorflow/lite/micro/kernels/squared_difference.su ./Core/Inc/tensorflow/lite/micro/kernels/squeeze.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/squeeze.d ./Core/Inc/tensorflow/lite/micro/kernels/squeeze.o ./Core/Inc/tensorflow/lite/micro/kernels/squeeze.su ./Core/Inc/tensorflow/lite/micro/kernels/strided_slice.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/strided_slice.d ./Core/Inc/tensorflow/lite/micro/kernels/strided_slice.o ./Core/Inc/tensorflow/lite/micro/kernels/strided_slice.su ./Core/Inc/tensorflow/lite/micro/kernels/strided_slice_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/strided_slice_common.d ./Core/Inc/tensorflow/lite/micro/kernels/strided_slice_common.o ./Core/Inc/tensorflow/lite/micro/kernels/strided_slice_common.su ./Core/Inc/tensorflow/lite/micro/kernels/sub.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/sub.d ./Core/Inc/tensorflow/lite/micro/kernels/sub.o ./Core/Inc/tensorflow/lite/micro/kernels/sub.su ./Core/Inc/tensorflow/lite/micro/kernels/sub_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/sub_common.d ./Core/Inc/tensorflow/lite/micro/kernels/sub_common.o ./Core/Inc/tensorflow/lite/micro/kernels/sub_common.su ./Core/Inc/tensorflow/lite/micro/kernels/svdf.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/svdf.d ./Core/Inc/tensorflow/lite/micro/kernels/svdf.o ./Core/Inc/tensorflow/lite/micro/kernels/svdf.su ./Core/Inc/tensorflow/lite/micro/kernels/svdf_common.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/svdf_common.d ./Core/Inc/tensorflow/lite/micro/kernels/svdf_common.o ./Core/Inc/tensorflow/lite/micro/kernels/svdf_common.su ./Core/Inc/tensorflow/lite/micro/kernels/tanh.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/tanh.d ./Core/Inc/tensorflow/lite/micro/kernels/tanh.o ./Core/Inc/tensorflow/lite/micro/kernels/tanh.su ./Core/Inc/tensorflow/lite/micro/kernels/transpose.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/transpose.d ./Core/Inc/tensorflow/lite/micro/kernels/transpose.o ./Core/Inc/tensorflow/lite/micro/kernels/transpose.su ./Core/Inc/tensorflow/lite/micro/kernels/transpose_conv.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/transpose_conv.d ./Core/Inc/tensorflow/lite/micro/kernels/transpose_conv.o ./Core/Inc/tensorflow/lite/micro/kernels/transpose_conv.su ./Core/Inc/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d ./Core/Inc/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o ./Core/Inc/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.su ./Core/Inc/tensorflow/lite/micro/kernels/unpack.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/unpack.d ./Core/Inc/tensorflow/lite/micro/kernels/unpack.o ./Core/Inc/tensorflow/lite/micro/kernels/unpack.su ./Core/Inc/tensorflow/lite/micro/kernels/var_handle.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/var_handle.d ./Core/Inc/tensorflow/lite/micro/kernels/var_handle.o ./Core/Inc/tensorflow/lite/micro/kernels/var_handle.su ./Core/Inc/tensorflow/lite/micro/kernels/while.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/while.d ./Core/Inc/tensorflow/lite/micro/kernels/while.o ./Core/Inc/tensorflow/lite/micro/kernels/while.su ./Core/Inc/tensorflow/lite/micro/kernels/zeros_like.cyclo ./Core/Inc/tensorflow/lite/micro/kernels/zeros_like.d ./Core/Inc/tensorflow/lite/micro/kernels/zeros_like.o ./Core/Inc/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-Core-2f-Inc-2f-tensorflow-2f-lite-2f-micro-2f-kernels

